### ISSUE TITLE
Proje Geliştirmesi sırasında kullanılacak Chat Programı

### ISSUE THREAD

**Issue by Yengas** [Yengas/KYCUBYO#3]
Projeler ile ilgili verilen kararların Proje Yönetimi yazılımı üzerinden yürütüleceği kesin. Projeler ile ilgili anlık mesajlaşma, kararları verirken yapılacak önemli olmayan yazışmalar için bir Chat programı belirlememiz lazım.

Yazılım sektöründe kullanılan benim bildiğim Slack, Hangouts var. Telegram, Whatsapp gibi bir kaç alternatifimiz daha var. WhatsApp açıkcası proje yönetimi/sohbet ayrımı konusunda sıkıntı çıkarabileceği için, ben pek taraftarı değilim.

Bu konuyu araştırıp, karar verelim.

**Comment by oguzcan-yavuz** [comment]
Hangouts daha önce kullanmadım ama Slack sohbet ayrımı konusunda baya iyi. Telegram'da ve Whatsapp'ta sohbet ayrımını Slack'teki gibi bir kanalda alt gruplar oluşturarak yapmak mümkün değil. Hangouts'u saymazsak diğer seçeneklere göre bence daha olası.

**Comment by Yengas** [comment]
Topluluk odasında yaptığımız konuşmalar neticesinde Slack kullanılmasına karar verilmiştir. Slack'in tercih edilmesindeki başlıca sebepler:

- Çoğu özelliğinin bedava olarak kullanılabilmesi
- Github entegrasyonu
- Topluluk altında geliştirilen projeler ve oluşturulan çalışma grupları için, chat grubu oluşturabilme ve bunları tek bir yerden takip edebilme.
- Windows Phone dahil çoğu platformda çalışabilmesi :D
- Chat geçmişinin kayıtlı olması
- Kolayca dosya paylaşılabilmesi
- Kolayca kod paylaşımı (snippet olarak veya dosya olarak) yapılabilmesi
