### ISSUE TITLE
Proje Geliştirme sırasında kullanılacak Proje Yönetim programı

### ISSUE THREAD

**Issue by Yengas** [Yengas/KYCUBYO#4]
Birden fazla proje ile, birden fazla takım ile çalışacağız. Bu yüzden genel durumu özetlemek ve birden fazla projeyi takip etmek için Github Issues yetersiz kalabilir. Herhangi bir proje yönetim yazılımı kullanacak mıyız? Bize avantajı olur mu? Bunu bu başlık altında tartışalım.

Benim bildiğim bir örnek Asana var. Takım oluşturma, kaç saat çalıştığını girme ve takım şeklinde proje yönetme özelliği var. Duyduğum bir kaç uygulama olarakta Jira, Trello, Teamwork var.

Bu konuda bu yazılımınn bize ne avantajı olacağını iyi düşünmemiz lazım. Gereksiz görürsek, proje bazlı direk Github Issues kullanabiliriz. Bir şirket gibi çalışmamıza gerek yok. Kim ne yaptı, ne kadar yaptıya kadar takip etmesekde olur herhalde?

**Comment by oguzcan-yavuz** [comment]
Trello'yu az önce ne gibi avantajları olabileceğini görmek için kullandım. Proje yönetimi konusunda Github Issues'in bize veremediği opsiyonlardan sadece konulara bitiş tarihi ekleme opsiyonunu görebildim. Geri kalan opsiyonları yalnızca board'lar ile daha güzel görünür bir şekilde yapıyor.  

Asana'yı da denedim ancak genel olarak proje yönetim yazılımlarının iki sebepten dolayı bizim için fazla komplike olduğunu düşünüyorum. Birincisi; kimin ne kadar çalıştığını takip etmemize gerek yok. Sadece kim hangi konuyla ilgileniyorsa onu görsek yeter diye düşünüyorum. Bunu da Github Issues ile yapabiliriz. İkincisi; bu tür yazılımların da bir adaptasyon süreci var. Projede yer alacak olan arkadaşlarımız zaten Git, Github, Docker gibi teknolojilere adapte olabilmek için belli bir zaman boyunca uğraşacaklar. Çok zorunda kalmadıkça bunlara ek olarak kullanımını öğrenmek için çaba harcanması gereken başka bir teknolojiyi kullanmama taraftarıyım. Yoksa sadece nasıl proje geliştireceğimiz konusunu öğrenene kadar gereğinden fazla vakit kaybedebiliriz ve bu kadar fazla teknolojiye birden adapte olmaya çalışmak bunaltıcı olabilir. 

Özet olarak bu yazılımların avantajı biraz daha düzen ve bitiş tarihi ekleyebilme opsiyonu. 
Sadece bitiş tarihi ekleme opsiyonumuzun olması için ek bir yazılım kullanmamıza değer mi? Bu konu hakkında düşünelim. Ancak benim fikrimce bizim için bu Github Issues yerine ek bir yazılım kullanmamızı gerektirecek kadar büyük bir avantaj değil.

**Comment by Yengas** [comment]
@yavuzovski Github Issues'da Milestones kullanarak issuelara Due Date verebiliyoruz. Ekstra bir platformun milleti bunaltabileceği konusunda haklısın. Bende o şekilde düşünüyorum. Fakat aklımdaki sorun Githubda çok sayıda proje oluşturmaya başlarsak, kimin ne yaptığını kolay bir şekilde göremeyebiliriz, takip etmesi zorlaşabilir.

[Şu tarz](https://www.atlassian.com/software/jira/comparison/jira-vs-github) yazılara baktıkca, bizim işimize yarayabilecek pek bir şey görmüyorum. Şimdilik Github Issue ile ilerlemek en mantıklısı olabilir. İleride yetersiz bulursak başka bir çözüm arayabiliriz.

Hem insanları açık kaynak projelerin işleyişine ve Github'ı aktif olarak kullanmayada teşvik etmiş oluruz. Bu da güzel bir artı olabilir.

**Comment by Yengas** [comment]
Github Issues kullanılmaya karar verildi.
