### ISSUE TITLE
Genel kullanım için Editör belirlenmesi

### ISSUE THREAD

**Issue by Yengas** [Yengas/KYCUBYO#5]
Öğrencilere bedava olduğu, kullanması çok avantajlı ve bolca plugin seçeneği olduğu için Jetbrains ürünleri ideal gibi görünüyor. Fakat benim eski laptopumda Jetbrains çalıştırırken sorun yaşıyordum. Performans konusunda sıkıntı yaşayanlar olabilir mi? Öyle ise bir alternatif belirlemek zorunda kalabiliriz.

Ayrıca bazı dil ve platformlar için istisna olabilir. Şimdilik kullanacağımız teknolojilerde aklıma öyle bir durum gelmiyor.

**Comment by oguzcan-yavuz** [comment]
Jetbrains ürünlerinin ideal olduğu konusunda hemfikirim. Sorun yaşayanlar olursa alternatif olarak Atom kullanılabilir.

**Comment by Yengas** [comment]
Jetbrains ürünleri kullanılmasına, kaynak kullanımı konusunda sıkıntı yaşayan arkadaşların Vim'e göz atmasına karar verilmiştir.
