### ISSUE TITLE
Döküman içeriklerinin TOC şeklinde özet olarak görüntülenebilmesi

### ISSUE THREAD

**Issue by Yengas** [Yengas/KYCUBYO#6]
Şuanda tüm konularda verilen kararları görmek oldukca kolay. Döküman büyüdükce klasör ve dosyalar arasında kaybolma durumu olabilir. Anasayfadaki README'ye bir TOC lazım. Döküman düzeni takip edilirse, basit bir script ile otomatik olarak oluşturulabilir.

Github pre-commit muhabbetine baktım. Bash ile yapılabilir gibi görünüyor. Windowsda sıkıntı olmayacak ise o şekilde yapılabilir. Her commit'den önce döküman yapısına göre bir TOC oluşturulur.

**Comment by oguzcan-yavuz** [comment]
Github'da  README.md dosyalarının veya Github wiki'lerinin TOC'unu çıkartan bir shell script hali hazırda var. Bunu kullanabiliriz.
https://github.com/ekalinin/github-markdown-toc

**Comment by Yengas** [comment]
@yavuzovski bu .md dosyalarını inceleyip, başlıklara göre TOC oluşturmak için kullanılıyor galiba. Bize custom bir script lazım gibi. Kodlaması basit olur muhtemelen. Tüm klasörleri listeleyip, klasörün README.md dosyası varsa link, yoksa label olarak alıcak, README.md dışındaki alt dosyalar için alt başlık ve link oluşturacak, sonra alt klasörler için recurse edicek tarzında.

**Comment by Yengas** [comment]
Şimdilik basit bir script proje ana dizininde [toc.py](https://github.com/Yengas/KYCUBYO/blob/master/toc.py) olarak bulunmakta. İlerleyen zamanda scriptin çalışmasını Wercker ile otomatik hale getirebilirim.

**Comment by Yengas** [comment]
Wercker ile otomatiğe bağlandı. Toc.py silindi. Ve ayrı bir Gist'e taşındı. https://gist.github.com/Yengas/609d2f76c175bfddba9ba9e39d6512a3
