### ISSUE TITLE
Github GUI ile ilgili kaynak eklenmesi.

### ISSUE THREAD

**Issue by Yengas** [Yengas/KYCUBYO#8]
Github'ı ve Git'i GUI ile kullanmayı tercih edenler olabilir. Bu konu hakkında araştırma yapıp, standart bir Git Workflowunda GUI ile nasıl çalışıldığının, ve Türkçe/İngilizce güzel kaynaklar varsa bunların Git kararına ekstra kaynak olarak eklenmesi.

**Comment by oguzcan-yavuz** [comment]
- [Github Masaüstü Uygulaması ile Versiyon Kontrolü](https://gelecegiyazanlar.turkcell.com.tr/blog/github-ile-surum-kontrolu) [Türkçe] [Giriş]

Git dökümanına eklendi.

**Comment by Yengas** [comment]
@yavuzovski TY
